const data = {
    products: [
      {
        _id:'1',
        name: 'Nike Slim shirt',
        slug: 'nike-slim-shirt',
        category: 'Shirts',
        image: '/images/p1.jpg', // 679px × 829px
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        _id:'2',
        name: 'Adidas Fit Shirt',
        slug: 'adidas-fit-shirt',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 250,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id:'3',
        name: 'Nike Slim Pant',
        slug: 'nike-slim-pant',
        category: 'Pants',
        image: '/images/p3.jpg',
        price: 25,
        countInStock: 15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id:'4',
        name: 'Adidas Fit Pant',
        slug: 'adidas-fit-pant',
        category: 'Pants',
        image: '/images/p4.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id:'5',
        name: 'Adidas Fit-1 Shirt',
        slug: 'adidas-fit-1-shirt',
        category: 'Shirts',
        image: '/images/p5.jpg',
        price: 250,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id:'6',
        name: 'nike-tshirt',
        slug: 'nike t-shirt',
        category: 'tshirt',
        image: '/images/p6.jpg',
        price: 250,
        countInStock: 20,
        brand: 'nike',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id:'7',
        name: 'iphone-6',
        slug: 'iphone',
        category: 'phone',
        image: '/images/phone1.jpg',
        price: 1250,
        countInStock: 20,
        brand: 'Apple',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id:'8',
        name: 'iphone-7',
        slug: 'iphone-1',
        category: 'phone',
        image: '/images/phone2.jpg',
        price: 2500,
        countInStock: 20,
        brand: 'Apple',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id:'9',
        name: 'iphone8',
        slug: 'iphone-8',
        category: 'phone',
        image: '/images/phone3.jpg',
        price: 200,
        countInStock: 20,
        brand: 'Apple',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id:'10',
        name: 'iphone-10',
        slug: 'iphone-2',
        category: 'phone',
        image: '/images/phone4.jpg',
        price: 2500,
        countInStock: 20,
        brand: 'Apple',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id:'11',
        name: 'samsung',
        slug: 'samsung-1',
        category: 'phone',
        image: '/images/phone5.jpg',
        price: 250,
        countInStock: 20,
        brand: 'Samsung',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id:'12',
        name: 'earphone',
        slug: 'earphone-1',
        category: 'earphone',
        image: '/images/ear5.jpg',
        price: 80,
        countInStock: 20,
        brand: 'Boat',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id:'13',
        name: 'Earphone',
        slug: 'Earphone-1',
        category: 'Earphone',
        image: '/images/ear4.jpg',
        price: 50,
        countInStock: 20,
        brand: 'vivo',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id:'14',
        name: 'Watch',
        slug: 'Watch-1',
        category: 'watch',
        image: '/images/watch6.jpg',
        price: 25,
        countInStock: 20,
        brand: 'Fossil',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id:'15',
        name: 'addidas-tshirt',
        slug: 'tshirt',
        category: 'black-tshirt',
        image: '/images/p6.jpg',
        price: 50,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
    ],
  };
  export default data;